import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_email_alert(
        transaction,
        risk_score,
        risk_level):

    sender_email = "YOUR_EMAIL@gmail.com"

    app_password = "YOUR_APP_PASSWORD"

    receiver_email = "YOUR_RECEIVER_EMAIL@gmail.com"

    subject = "🚨 Financial Fraud Alert"

    body = f"""
🚨 FRAUD DETECTION ALERT 🚨

Transaction Type : {transaction['type']}

Amount           : ₹{transaction['amount']}

Sender           : {transaction['nameOrig']}

Receiver         : {transaction['nameDest']}

Risk Score       : {risk_score}

Risk Level       : {risk_level}

Generated By:
Financial Fraud Detection System
"""

    message = MIMEMultipart()

    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    message.attach(
        MIMEText(body, "plain")
    )

    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            sender_email,
            app_password
        )

        server.sendmail(
            sender_email,
            receiver_email,
            message.as_string()
        )

        server.quit()

        print("📧 Email Alert Sent Successfully")

    except Exception as e:

        print("❌ Email Error :", e)